[package]
name = "Crisp"
version = "0.1.0"
authors = ["Xavian Ogletree <xavian.ogletree@outlook.com.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.7.0"
cairo-rs = "^0"
gio = "^0"
gdk = "^0"
